### ISSUE TITLE
add_css text-align centre not working with shiny

### ISSUE THREAD

**Issue by jamesthomson** [LyzandeR/tableHTML#1]
the tableHTML works fine within R, but when you do it in a shiny app the headers of the table come out left aligned.

`    output$viewers_website_top<-renderUI({
      tableHTML(website_index, rownames = FALSE, widths=c(200,200)) %>%
        add_css_column(css = list("text-align", "center"), column_names = names(website_index)) 
    })`

is there something in shiny that causes this, or do i need to amend my code?

**Comment by LyzandeR** [comment]
This is a known problem with css in bootstrap 3 actually. Whenever you use shiny, it loads up a bootstrap 3 css first, which essentially cannot be overwritten. The way to fix this is to add a css file using the `shiny::includeCSS` function. The file should contain the following:

```r
.table_website_index th {
  text-align: center
}
```

Initially I thought that adding !important in the inline html (i.e. using `add_css_column(css = list("text-align", "center !important"`) would work but apparently it doesn't accept it. I think the above is probably the only way to do it.

P.S. table_website_index is the class tableHTML creates for your table automatically (which can be altered through the `class` argument.

**Comment by jamesthomson** [comment]
Great thanks for the quick response.
Perhaps it would be worth adding a function to the package to auto generate this css file for you.

**Comment by LyzandeR** [comment]
This is a brilliant idea! This can definitely be added in the new version of tableHTML. Do you mind adding it as a new issue in order to keep these separated?
