### ISSUE TITLE
New tableHTML attributes

### ISSUE THREAD

**Issue by clemens-zauchner** [LyzandeR/tableHTML#10]
I think we would benefit from including additional attributes to the tableHTML object.
- number of columns
- number of rows
- data types for columns
- flag if rownames, rowgroups, and second headers are present

As an alternative the whole original table could be one of the attributes (e.g. "data"), but it might not be practical with big tables.

**Comment by theo-boutaris-sainsburys** [comment]
Let's start with the bullet points first :)

If rownames, rowgroups and second headers are present how would this affect the two first bullet points? Shall I just use nrow and ncol on the data and report that as an attribute?

**Comment by LyzandeR** [comment]
If rownames, rowgroups or second headers exist, how would that affect the first two bullet points? Shall I just use nrow and ncol on the data?

**Comment by clemens-zauchner** [comment]
ncol and nrow should be fine and would be most intuitive i guess.

**Comment by LyzandeR** [comment]
@clemens-zauchner  Attributes added and pull request merged! Should be able to see it on master and pull to your branch. Added tests as well.

**Comment by clemens-zauchner** [comment]
i think it would be beneficial to add flags (rownames, rowgroups, and second headers) to the attributes the tableHTML class for checks. at the moment, a tableHTML can be created like this:
`tableHTML(mtcars, rownames = FALSE)` and then you can do this:
`tableHTML(mtcars, rownames = FALSE) %>% add_css_column(columns = "rownames", css = list ("background-color", "red"))` which would do nothing to the tableHTML. In the case of conditional formatting, it creates an error in this situation, so i need it for checks to prevent this.

**Comment by LyzandeR** [comment]
Will add those asap.

**Comment by LyzandeR** [comment]
Additional attributes have been added to master!
