### ISSUE TITLE
format options in tableHTML

### ISSUE THREAD

**Issue by clemens-zauchner** [LyzandeR/tableHTML#18]
Would it be a good idea to include an option to replace NA or round numeric values when building the table? something like
```
data.frame(a = c(1, NA, 3), b = c(5.456713158687324, 6.1154, 4.74541)) %>% 
  tableHTML(rownames = FALSE,
            round_digits = 2,
            replace_NA = TRUE)
```

instead of

![screen shot 2018-01-11 at 15 30 59](https://user-images.githubusercontent.com/29435287/34830554-86f9cd60-f6e4-11e7-8ea2-23e314c80a87.png)

you would get

![screen shot 2018-01-11 at 15 30 37](https://user-images.githubusercontent.com/29435287/34830562-8cbd20c6-f6e4-11e7-9f17-94ca92b1026b.png)

**Comment by LyzandeR** [comment]
I can do this one, good call.

**Comment by vnckppl** [comment]
Copying and pasting this code still shows NA for me. What is the proper way to not display these values?
