### ISSUE TITLE
add data to tableHTML object attributes

### ISSUE THREAD

**Issue by clemens-zauchner** [LyzandeR/tableHTML#19]
I think it would make sense to include the original data as an attribute of the tableHTML object. we could add a `limitsize` similar to ggsave in ggplot2 [When TRUE (the default), ggsave will not save images larger than 50x50 inches, to prevent the common error of specifying dimensions in pixels]

It would make some things easier, e.g.

- conditional formatting
- a round parameter
- merge and center cells

**Comment by LyzandeR** [comment]
I agree. Let's add this.

What would limitsize be in our case?

**Comment by clemens-zauchner** [comment]
We have decided not to add a limitsize, but instead have an arguemnt `add_data` which defaluts to `TRUE`. This is because `add_css_conditional_column` requires the data in the next version. If no conditional formatting is used, the parameter can be set to `FALSE` to restrict the object size.
