### ISSUE TITLE
Create a function that creates a css file to correct text alignment

### ISSUE THREAD

**Issue by jamesthomson** [LyzandeR/tableHTML#2]
as discussed in a previous issue #1 [here](https://github.com/LyzandeR/tableHTML/issues/1)

create a function that generates a css file for use in a shiny app to align text in a table and overrule the bootstrap css

**Comment by LyzandeR** [comment]
Brilliant! This is a very good idea actually. I ll create a function to be released in the next version. Thanks.

**Comment by LyzandeR** [comment]
`make_css` implements the idea above. Version 0.2.11 is now on CRAN.
