### ISSUE TITLE
Making tableHTML conform to tidyverse conventions

### ISSUE THREAD

**Issue by smithjd** [LyzandeR/tableHTML#4]
It would be nice if tableHTML conformed to the tidyverse custom of working with magrittr chaining. 

So for example, it would be nice to say:

`df %>% tableHTML(rownames = FALSE)`

Instead of the current:

`df %>% tableHTML(., rownames = FALSE)`

(GREAT package, by the way!)

**Comment by LyzandeR** [comment]
Thanks for your kind words @smithjd .

As far as I can tell `df %>% tableHTML(rownames = FALSE)` works just fine for me (this is the standard way and it is demonstrated in the [tutorial](https://cran.r-project.org/web/packages/tableHTML/vignettes/tableHTML.html) as well (scroll down to the add_css_* functions). Are you sure that the pipe operator wasn't masked when you tried running it? I am not an expert in Hadley's tidyverse style but the package was designed to work with magrittr chaining.

If your problem persists please post another example and I will definitely look into it.

**Comment by smithjd** [comment]
ooops.  you are right!  Thanks!
