### ISSUE TITLE
add subscript and superscript

### ISSUE THREAD

**Issue by msgoussi** [LyzandeR/tableHTML#40]
I am trying to add superscript to dataframe  element

library(tableHTML)
dataset <- mtcars[1:3,1:3]
dataset[3, 3] <- paste0(108, "\\textsuperscript{5}")
write_tableHTML(tableHTML(dataset), "x.html")

Thanks

**Comment by clemens-zauchner** [comment]
You can use the HTML <sup>`-tag to achieche just that:

```
library(tableHTML)
dataset <- mtcars[1:3,1:3]
dataset[3, 3] <- paste0(108, "<sup>5</sup>")

dataset %>% 
  tableHTML(escape = FALSE) %>% 
  write_tableHTML("x.html")
```
The result would be:
![result](https://user-images.githubusercontent.com/29435287/54903881-3a0a4000-4edd-11e9-8b14-fb2e2323a7ce.png)
