### ISSUE TITLE
tableHTML not working within a for-loop on r-markdown

### ISSUE THREAD

**Issue by LyzandeR** [LyzandeR/tableHTML#44]
I was trying to print a number of `tableHTML`s within a for-loop on rmarkdown and it didn't work.

Reproducible example:

```
for (i in 1:2) {

  tableHTML(mtcars)

}
```

I tried `print`ing the result or using `htmltools::print_html` but nothing worked

**Comment by clemens-zauchner** [comment]
You need to explicitly call print in the for-loop and then use `results='asis'` in your code chunk to maek sure that the returned HTML is rendered:

```
```{r, results='asis'}
for (i in 1:2) {

  tableHTML(mtcars) %>% 
    print()

}

`````
