### ISSUE TITLE
Save changes to editable column

### ISSUE THREAD

**Issue by bes828** [LyzandeR/tableHTML#48]
Hello
I created a table with editable column using `add_editable_column` function. 
Is there a way to "save" the edits? ie they remain after refreshing or reopening the file? 
I asked a colleague who works with webpages and apparently this is a complex process that requires javascript tags. Was wondering if there is a way to add this js tag using this package or any other method to achieve the desired output. 

thank you

**Comment by LyzandeR** [comment]
Hi @bes828 
Thanks for posting a question.

Your colleague is correct. Updating the underlying data.frame is not the easiest process. It definitely cannot happen with in-line HTML code (or CSS), which is tableHTML's (current) scope. We added the editable HTML tag in the package to help people, who build shiny applications / web applications, capture the edits with JS code. 

So it is not something that you can do with the tableHTML package right now. However, we might investigate / research it in the future!

P.S. we do encourage Merge Requests if you do your own research and find a way :)

**Comment by clemens-zauchner** [comment]
Yes, @LyzandeR is right. For that to work, you would probably need to use Javascript within Shiny to get the data back to R. We have not yet finished investigating whether such a thing is possible without too much of a dirty hack. 

The idea is to have a Javascript event and define an action in shiny that is triggered whenever the event occurs. This is possible I think, but exchanging data within that process might be harder

**Comment by bes828** [comment]
@LyzandeR @clemens-zauchner 
I appreciate your answers to my questions. I totally I understand that this is a complex task and I did not expect it to  be possible by HTML alone but it does not hurt to ask!
thanks for the great package. I will update this thread if I find something relevant.

**Comment by LyzandeR** [comment]
@bes828 Thank you very much! It absolutely doesn't hurt to ask and we are very happy to help whenever we can!

I am closing this for now, but can easily re-open later on if there is an update.
